import type { SerializedSandboxPrefab } from "../SandboxPrefabs";

export const dominoLinePrefab: SerializedSandboxPrefab = {
  id: "domino-line",
  name: "Domino Line",
  description:
    "A starter ball and a line of thin blocks for chain-reaction collision testing. [Try picking up the ball and knocking it gently into the dominoes]",
  objects: [
    {
      id: "domino-line-floor",
      name: "Domino Floor",
      type: "Platform",
      position: { x: 0, y: 155 },
      offset: { x: 0, y: 155 },
      angle: 0,
      flags: 4,
      metadata: {
        opacity: 1,
        borderWidth: 1,
        borderStyle: "Solid",
        mass: 5,
        bounce: 0.5,
        friction: 0.2,
        radialForceMode: "None",
        radialForceRadius: 240,
        radialForceStrength: 0.0012,
        width: 720,
        height: 28,
        color: "#565656",
        borderColor: "#8a8a8a",
        label: "Platform",
        description: "Static platform body",
        collisionRole: 0,
      },
    },
    {
      id: "domino-line-starter-ball",
      name: "Starter Ball",
      type: "Circle",
      position: { x: -310, y: 95 },
      offset: { x: -310, y: 95 },
      angle: 0,
      flags: 0,
      metadata: {
        opacity: 1,
        borderWidth: 1,
        borderStyle: "Solid",
        mass: 8,
        bounce: 0.5,
        friction: 0.01,
        radialForceMode: "None",
        radialForceRadius: 240,
        radialForceStrength: 0.0012,
        width: 56,
        height: 56,
        color: "#4f8cff",
        borderColor: "#b8d0ff",
        label: "Circle",
        description: "Dynamic circular body",
        collisionRole: 1,
      },
    },
    {
      id: "domino-line-domino-1",
      name: "Domino 1",
      type: "Box",
      position: { x: -170, y: 92 },
      offset: { x: -170, y: 92 },
      angle: 0,
      flags: 0,
      metadata: {
        opacity: 1,
        borderWidth: 1,
        borderStyle: "Solid",
        mass: 1.2,
        bounce: 0.2,
        friction: 0.01,
        radialForceMode: "None",
        radialForceRadius: 240,
        radialForceStrength: 0.0012,
        width: 10,
        height: 90,
        color: "#e2d37a",
        borderColor: "#fff1a8",
        label: "Box",
        description: "Dynamic rectangular body",
        collisionRole: 1,
      },
    },
    {
      id: "domino-line-domino-2",
      name: "Domino 2",
      type: "Box",
      position: { x: -136, y: 92 },
      offset: { x: -136, y: 92 },
      angle: 0,
      flags: 0,
      metadata: {
        opacity: 1,
        borderWidth: 1,
        borderStyle: "Solid",
        mass: 1.2,
        bounce: 0.2,
        friction: 0.01,
        radialForceMode: "None",
        radialForceRadius: 240,
        radialForceStrength: 0.0012,
        width: 10,
        height: 90,
        color: "#e2d37a",
        borderColor: "#fff1a8",
        label: "Box",
        description: "Dynamic rectangular body",
        collisionRole: 1,
      },
    },
    {
      id: "domino-line-domino-3",
      name: "Domino 3",
      type: "Box",
      position: { x: -102, y: 92 },
      offset: { x: -102, y: 92 },
      angle: 0,
      flags: 0,
      metadata: {
        opacity: 1,
        borderWidth: 1,
        borderStyle: "Solid",
        mass: 1.2,
        bounce: 0.2,
        friction: 0.01,
        radialForceMode: "None",
        radialForceRadius: 240,
        radialForceStrength: 0.0012,
        width: 10,
        height: 90,
        color: "#e2d37a",
        borderColor: "#fff1a8",
        label: "Box",
        description: "Dynamic rectangular body",
        collisionRole: 1,
      },
    },
    {
      id: "domino-line-domino-4",
      name: "Domino 4",
      type: "Box",
      position: { x: -68, y: 92 },
      offset: { x: -68, y: 92 },
      angle: 0,
      flags: 0,
      metadata: {
        opacity: 1,
        borderWidth: 1,
        borderStyle: "Solid",
        mass: 1.2,
        bounce: 0.2,
        friction: 0.01,
        radialForceMode: "None",
        radialForceRadius: 240,
        radialForceStrength: 0.0012,
        width: 10,
        height: 90,
        color: "#e2d37a",
        borderColor: "#fff1a8",
        label: "Box",
        description: "Dynamic rectangular body",
        collisionRole: 1,
      },
    },
    {
      id: "domino-line-domino-5",
      name: "Domino 5",
      type: "Box",
      position: { x: -34, y: 92 },
      offset: { x: -34, y: 92 },
      angle: 0,
      flags: 0,
      metadata: {
        opacity: 1,
        borderWidth: 1,
        borderStyle: "Solid",
        mass: 1.2,
        bounce: 0.2,
        friction: 0.01,
        radialForceMode: "None",
        radialForceRadius: 240,
        radialForceStrength: 0.0012,
        width: 10,
        height: 90,
        color: "#e2d37a",
        borderColor: "#fff1a8",
        label: "Box",
        description: "Dynamic rectangular body",
        collisionRole: 1,
      },
    },
    {
      id: "domino-line-domino-6",
      name: "Domino 6",
      type: "Box",
      position: { x: 0, y: 92 },
      offset: { x: 0, y: 92 },
      angle: 0,
      flags: 0,
      metadata: {
        opacity: 1,
        borderWidth: 1,
        borderStyle: "Solid",
        mass: 1.2,
        bounce: 0.2,
        friction: 0.01,
        radialForceMode: "None",
        radialForceRadius: 240,
        radialForceStrength: 0.0012,
        width: 10,
        height: 90,
        color: "#e2d37a",
        borderColor: "#fff1a8",
        label: "Box",
        description: "Dynamic rectangular body",
        collisionRole: 1,
      },
    },
    {
      id: "domino-line-domino-7",
      name: "Domino 7",
      type: "Box",
      position: { x: 34, y: 92 },
      offset: { x: 34, y: 92 },
      angle: 0,
      flags: 0,
      metadata: {
        opacity: 1,
        borderWidth: 1,
        borderStyle: "Solid",
        mass: 1.2,
        bounce: 0.2,
        friction: 0.01,
        radialForceMode: "None",
        radialForceRadius: 240,
        radialForceStrength: 0.0012,
        width: 10,
        height: 90,
        color: "#e2d37a",
        borderColor: "#fff1a8",
        label: "Box",
        description: "Dynamic rectangular body",
        collisionRole: 1,
      },
    },
    {
      id: "domino-line-domino-8",
      name: "Domino 8",
      type: "Box",
      position: { x: 68, y: 92 },
      offset: { x: 68, y: 92 },
      angle: 0,
      flags: 0,
      metadata: {
        opacity: 1,
        borderWidth: 1,
        borderStyle: "Solid",
        mass: 1.2,
        bounce: 0.2,
        friction: 0.01,
        radialForceMode: "None",
        radialForceRadius: 240,
        radialForceStrength: 0.0012,
        width: 10,
        height: 90,
        color: "#e2d37a",
        borderColor: "#fff1a8",
        label: "Box",
        description: "Dynamic rectangular body",
        collisionRole: 1,
      },
    },
    {
      id: "domino-line-domino-9",
      name: "Domino 9",
      type: "Box",
      position: { x: 102, y: 92 },
      offset: { x: 102, y: 92 },
      angle: 0,
      flags: 0,
      metadata: {
        opacity: 1,
        borderWidth: 1,
        borderStyle: "Solid",
        mass: 1.2,
        bounce: 0.2,
        friction: 0.01,
        radialForceMode: "None",
        radialForceRadius: 240,
        radialForceStrength: 0.0012,
        width: 10,
        height: 90,
        color: "#e2d37a",
        borderColor: "#fff1a8",
        label: "Box",
        description: "Dynamic rectangular body",
        collisionRole: 1,
      },
    },
    {
      id: "domino-line-domino-10",
      name: "Domino 10",
      type: "Box",
      position: { x: 136, y: 92 },
      offset: { x: 136, y: 92 },
      angle: 0,
      flags: 0,
      metadata: {
        opacity: 1,
        borderWidth: 1,
        borderStyle: "Solid",
        mass: 1.2,
        bounce: 0.2,
        friction: 0.01,
        radialForceMode: "None",
        radialForceRadius: 240,
        radialForceStrength: 0.0012,
        width: 10,
        height: 90,
        color: "#e2d37a",
        borderColor: "#fff1a8",
        label: "Box",
        description: "Dynamic rectangular body",
        collisionRole: 1,
      },
    },
    {
      id: "domino-line-domino-11",
      name: "Domino 11",
      type: "Box",
      position: { x: 170, y: 92 },
      offset: { x: 170, y: 92 },
      angle: 0,
      flags: 0,
      metadata: {
        opacity: 1,
        borderWidth: 1,
        borderStyle: "Solid",
        mass: 1.2,
        bounce: 0.2,
        friction: 0.01,
        radialForceMode: "None",
        radialForceRadius: 240,
        radialForceStrength: 0.0012,
        width: 10,
        height: 90,
        color: "#e2d37a",
        borderColor: "#fff1a8",
        label: "Box",
        description: "Dynamic rectangular body",
        collisionRole: 1,
      },
    },
    {
      id: "domino-line-domino-12",
      name: "Domino 12",
      type: "Box",
      position: { x: 204, y: 92 },
      offset: { x: 204, y: 92 },
      angle: 0,
      flags: 0,
      metadata: {
        opacity: 1,
        borderWidth: 1,
        borderStyle: "Solid",
        mass: 1.2,
        bounce: 0.2,
        friction: 0.01,
        radialForceMode: "None",
        radialForceRadius: 240,
        radialForceStrength: 0.0012,
        width: 10,
        height: 90,
        color: "#e2d37a",
        borderColor: "#fff1a8",
        label: "Box",
        description: "Dynamic rectangular body",
        collisionRole: 1,
      },
    },
  ],
};
