import type { SerializedSandboxPrefab } from "../SandboxPrefabs";

export const platformStackPrefab: SerializedSandboxPrefab = {
  id: "platform-stack",
  name: "Platform Stack",
  description: "A static platform with three dynamic objects above it.",
  objects: [
    {
      id: "platform-stack-platform",
      name: "Prefab Platform",
      type: "Platform",
      position: { x: 0, y: 90 },
      offset: { x: 0, y: 90 },
      angle: 0,
      flags: 4,
      metadata: {
        opacity: 1,
        borderWidth: 1,
        borderStyle: "Solid",
        mass: 5,
        bounce: 0.5,
        friction: 0.01,
        radialForceMode: "None",
        radialForceRadius: 240,
        radialForceStrength: 0.0012,
        width: 240,
        height: 28,
        color: "#565656",
        borderColor: "#8a8a8a",
        label: "Platform",
        description: "Static platform body",
        collisionRole: 0,
      },
    },
    {
      id: "platform-stack-box",
      name: "Prefab Box",
      type: "Box",
      position: { x: -54, y: 20 },
      offset: { x: -54, y: 20 },
      angle: 0,
      flags: 0,
      metadata: {
        opacity: 1,
        borderWidth: 1,
        borderStyle: "Solid",
        mass: 5,
        bounce: 0.5,
        friction: 0.01,
        radialForceMode: "None",
        radialForceRadius: 240,
        radialForceStrength: 0.0012,
        width: 50,
        height: 50,
        color: "#7cce83",
        borderColor: "#d6ffd9",
        label: "Box",
        description: "Dynamic rectangular body",
        collisionRole: 1,
      },
    },
    {
      id: "platform-stack-circle",
      name: "Prefab Circle",
      type: "Circle",
      position: { x: 0, y: -38 },
      offset: { x: 0, y: -38 },
      angle: 0,
      flags: 0,
      metadata: {
        opacity: 1,
        borderWidth: 1,
        borderStyle: "Solid",
        mass: 5,
        bounce: 0.5,
        friction: 0.01,
        radialForceMode: "None",
        radialForceRadius: 240,
        radialForceStrength: 0.0012,
        width: 50,
        height: 50,
        color: "#4f8cff",
        borderColor: "#b8d0ff",
        label: "Circle",
        description: "Dynamic circular body",
        collisionRole: 1,
      },
    },
    {
      id: "platform-stack-triangle",
      name: "Prefab Triangle",
      type: "Triangle",
      position: { x: 58, y: 18 },
      offset: { x: 58, y: 18 },
      angle: 0,
      flags: 0,
      metadata: {
        opacity: 1,
        borderWidth: 1,
        borderStyle: "Solid",
        mass: 5,
        bounce: 0.5,
        friction: 0.01,
        radialForceMode: "None",
        radialForceRadius: 240,
        radialForceStrength: 0.0012,
        width: 64,
        height: 64,
        color: "#f2b84b",
        borderColor: "#ffe1a0",
        label: "Triangle",
        description: "Dynamic triangular body",
        collisionRole: 1,
      },
    },
  ],
};
