import type { SerializedSandboxPrefab } from "../SandboxPrefabs";

export const repulsionChamberPrefab: SerializedSandboxPrefab = {
  id: "repulsion-chamber",
  name: "Repulsion Chamber",
  description:
    "A contained white-hole force source with dynamic test objects around it.",
  objects: [
    {
      id: "repulsion-chamber-floor",
      name: "Chamber Floor",
      type: "Platform",
      position: { x: 0, y: 205 },
      offset: { x: 0, y: 205 },
      angle: 0,
      flags: 4,
      metadata: {
        opacity: 1,
        borderWidth: 1,
        borderStyle: "Solid",
        mass: 5,
        bounce: 0.5,
        friction: 0.01,
        radialForceMode: "None",
        radialForceRadius: 240,
        radialForceStrength: 0.0012,
        width: 500,
        height: 28,
        color: "#565656",
        borderColor: "#8a8a8a",
        label: "Platform",
        description: "Static platform body",
        collisionRole: 0,
      },
    },
    {
      id: "repulsion-chamber-ceiling",
      name: "Chamber Ceiling",
      type: "Platform",
      position: { x: 0, y: -205 },
      offset: { x: 0, y: -205 },
      angle: 0,
      flags: 4,
      metadata: {
        opacity: 1,
        borderWidth: 1,
        borderStyle: "Solid",
        mass: 5,
        bounce: 0.5,
        friction: 0.01,
        radialForceMode: "None",
        radialForceRadius: 240,
        radialForceStrength: 0.0012,
        width: 500,
        height: 28,
        color: "#565656",
        borderColor: "#8a8a8a",
        label: "Platform",
        description: "Static platform body",
        collisionRole: 0,
      },
    },
    {
      id: "repulsion-chamber-left-wall",
      name: "Chamber Left Wall",
      type: "Wall",
      position: { x: -260, y: 0 },
      offset: { x: -260, y: 0 },
      angle: 0,
      flags: 4,
      metadata: {
        opacity: 1,
        borderWidth: 1,
        borderStyle: "Solid",
        mass: 5,
        bounce: 0.5,
        friction: 0.01,
        radialForceMode: "None",
        radialForceRadius: 240,
        radialForceStrength: 0.0012,
        width: 36,
        height: 430,
        color: "#5c5c5c",
        borderColor: "#929292",
        label: "Wall",
        description: "Static vertical wall body",
        collisionRole: 0,
      },
    },
    {
      id: "repulsion-chamber-right-wall",
      name: "Chamber Right Wall",
      type: "Wall",
      position: { x: 260, y: 0 },
      offset: { x: 260, y: 0 },
      angle: 0,
      flags: 4,
      metadata: {
        opacity: 1,
        borderWidth: 1,
        borderStyle: "Solid",
        mass: 5,
        bounce: 0.5,
        friction: 0.01,
        radialForceMode: "None",
        radialForceRadius: 240,
        radialForceStrength: 0.0012,
        width: 36,
        height: 430,
        color: "#5c5c5c",
        borderColor: "#929292",
        label: "Wall",
        description: "Static vertical wall body",
        collisionRole: 0,
      },
    },
    {
      id: "repulsion-chamber-repulsor",
      name: "Repulsor",
      type: "WhiteHole",
      position: { x: 0, y: 0 },
      offset: { x: 0, y: 0 },
      angle: 0,
      flags: 4,
      metadata: {
        opacity: 1,
        borderWidth: 1,
        borderStyle: "Solid",
        mass: 5,
        bounce: 0.5,
        friction: 0.01,
        radialForceMode: "Push",
        radialForceRadius: 260,
        radialForceStrength: 0.006,
        width: 60,
        height: 60,
        color: "#f5f7ff",
        borderColor: "#88b8ff",
        label: "White Hole",
        description: "Static circular body with a strong push force",
        collisionRole: 0,
      },
    },
    {
      id: "repulsion-chamber-test-1",
      name: "Repulsion Test 1",
      type: "Circle",
      position: { x: 145, y: 0 },
      offset: { x: 145, y: 0 },
      angle: 0,
      flags: 0,
      metadata: {
        opacity: 1,
        borderWidth: 1,
        borderStyle: "Solid",
        mass: 3,
        bounce: 0.5,
        friction: 0.01,
        radialForceMode: "None",
        radialForceRadius: 240,
        radialForceStrength: 0.0012,
        width: 50,
        height: 50,
        color: "#4f8cff",
        borderColor: "#b8d0ff",
        label: "Circle",
        description: "Dynamic circular body",
        collisionRole: 1,
      },
    },
    {
      id: "repulsion-chamber-test-2",
      name: "Repulsion Test 2",
      type: "Box",
      position: { x: 102.5305, y: 81.3173 },
      offset: { x: 102.5305, y: 81.3173 },
      angle: 0,
      flags: 0,
      metadata: {
        opacity: 1,
        borderWidth: 1,
        borderStyle: "Solid",
        mass: 3,
        bounce: 0.5,
        friction: 0.01,
        radialForceMode: "None",
        radialForceRadius: 240,
        radialForceStrength: 0.0012,
        width: 50,
        height: 50,
        color: "#7cce83",
        borderColor: "#d6ffd9",
        label: "Box",
        description: "Dynamic rectangular body",
        collisionRole: 1,
      },
    },
    {
      id: "repulsion-chamber-test-3",
      name: "Repulsion Test 3",
      type: "Circle",
      position: { x: 0, y: 115 },
      offset: { x: 0, y: 115 },
      angle: 0,
      flags: 0,
      metadata: {
        opacity: 1,
        borderWidth: 1,
        borderStyle: "Solid",
        mass: 3,
        bounce: 0.5,
        friction: 0.01,
        radialForceMode: "None",
        radialForceRadius: 240,
        radialForceStrength: 0.0012,
        width: 50,
        height: 50,
        color: "#4f8cff",
        borderColor: "#b8d0ff",
        label: "Circle",
        description: "Dynamic circular body",
        collisionRole: 1,
      },
    },
    {
      id: "repulsion-chamber-test-4",
      name: "Repulsion Test 4",
      type: "Box",
      position: { x: -102.5305, y: 81.3173 },
      offset: { x: -102.5305, y: 81.3173 },
      angle: 0,
      flags: 0,
      metadata: {
        opacity: 1,
        borderWidth: 1,
        borderStyle: "Solid",
        mass: 3,
        bounce: 0.5,
        friction: 0.01,
        radialForceMode: "None",
        radialForceRadius: 240,
        radialForceStrength: 0.0012,
        width: 50,
        height: 50,
        color: "#7cce83",
        borderColor: "#d6ffd9",
        label: "Box",
        description: "Dynamic rectangular body",
        collisionRole: 1,
      },
    },
    {
      id: "repulsion-chamber-test-5",
      name: "Repulsion Test 5",
      type: "Circle",
      position: { x: -145, y: 0 },
      offset: { x: -145, y: 0 },
      angle: 0,
      flags: 0,
      metadata: {
        opacity: 1,
        borderWidth: 1,
        borderStyle: "Solid",
        mass: 3,
        bounce: 0.5,
        friction: 0.01,
        radialForceMode: "None",
        radialForceRadius: 240,
        radialForceStrength: 0.0012,
        width: 50,
        height: 50,
        color: "#4f8cff",
        borderColor: "#b8d0ff",
        label: "Circle",
        description: "Dynamic circular body",
        collisionRole: 1,
      },
    },
    {
      id: "repulsion-chamber-test-6",
      name: "Repulsion Test 6",
      type: "Box",
      position: { x: -102.5305, y: -81.3173 },
      offset: { x: -102.5305, y: -81.3173 },
      angle: 0,
      flags: 0,
      metadata: {
        opacity: 1,
        borderWidth: 1,
        borderStyle: "Solid",
        mass: 3,
        bounce: 0.5,
        friction: 0.01,
        radialForceMode: "None",
        radialForceRadius: 240,
        radialForceStrength: 0.0012,
        width: 50,
        height: 50,
        color: "#7cce83",
        borderColor: "#d6ffd9",
        label: "Box",
        description: "Dynamic rectangular body",
        collisionRole: 1,
      },
    },
    {
      id: "repulsion-chamber-test-7",
      name: "Repulsion Test 7",
      type: "Circle",
      position: { x: 0, y: -115 },
      offset: { x: 0, y: -115 },
      angle: 0,
      flags: 0,
      metadata: {
        opacity: 1,
        borderWidth: 1,
        borderStyle: "Solid",
        mass: 3,
        bounce: 0.5,
        friction: 0.01,
        radialForceMode: "None",
        radialForceRadius: 240,
        radialForceStrength: 0.0012,
        width: 50,
        height: 50,
        color: "#4f8cff",
        borderColor: "#b8d0ff",
        label: "Circle",
        description: "Dynamic circular body",
        collisionRole: 1,
      },
    },
    {
      id: "repulsion-chamber-test-8",
      name: "Repulsion Test 8",
      type: "Box",
      position: { x: 102.5305, y: -81.3173 },
      offset: { x: 102.5305, y: -81.3173 },
      angle: 0,
      flags: 0,
      metadata: {
        opacity: 1,
        borderWidth: 1,
        borderStyle: "Solid",
        mass: 3,
        bounce: 0.5,
        friction: 0.01,
        radialForceMode: "None",
        radialForceRadius: 240,
        radialForceStrength: 0.0012,
        width: 50,
        height: 50,
        color: "#7cce83",
        borderColor: "#d6ffd9",
        label: "Box",
        description: "Dynamic rectangular body",
        collisionRole: 1,
      },
    },
  ],
};
