import type { SerializedSandboxPrefab } from "../SandboxPrefabs";

export const solarSandboxPrefab: SerializedSandboxPrefab = {
  id: "solar-sandbox",
  name: "Solar Sandbox",
  description:
    "A smaller Sun, Earth, and Moon gravity setup for focused experimentation. [Tip: Reduce or disable global gravity.]",
  objects: [
    {
      id: "solar-sandbox-sun",
      name: "Solar Sandbox Sun",
      type: "Sun",
      position: { x: 0, y: 0 },
      offset: { x: 0, y: 0 },
      angle: 0,
      flags: 4,
      metadata: {
        opacity: 1,
        borderWidth: 1,
        borderStyle: "Solid",
        mass: 5,
        bounce: 0.5,
        friction: 0.01,
        radialForceMode: "Pull",
        radialForceRadius: 330,
        radialForceStrength: 0.004,
        width: 60,
        height: 60,
        color: "#f6c453",
        borderColor: "#fff0a8",
        label: "Sun",
        description: "Static circular body with a strong pull force",
        collisionRole: 0,
      },
    },
    {
      id: "solar-sandbox-earth",
      name: "Solar Sandbox Earth",
      type: "Circle",
      position: { x: 390, y: -80 },
      offset: { x: 390, y: -80 },
      angle: 0,
      flags: 4,
      metadata: {
        opacity: 1,
        borderWidth: 1,
        borderStyle: "Solid",
        mass: 5,
        bounce: 0.5,
        friction: 0.01,
        radialForceMode: "Pull",
        radialForceRadius: 175,
        radialForceStrength: 0.0014,
        width: 80,
        height: 80,
        color: "#2f74c0",
        borderColor: "#7ac88f",
        label: "Earth",
        description: "Dynamic circular body",
        collisionRole: 1,
      },
    },
    {
      id: "solar-sandbox-moon",
      name: "Solar Sandbox Moon",
      type: "Circle",
      position: { x: 510, y: -145 },
      offset: { x: 510, y: -145 },
      angle: 0,
      flags: 4,
      metadata: {
        opacity: 1,
        borderWidth: 1,
        borderStyle: "Solid",
        mass: 5,
        bounce: 0.5,
        friction: 0.01,
        radialForceMode: "Pull",
        radialForceRadius: 75,
        radialForceStrength: 0.0003,
        width: 34,
        height: 34,
        color: "#b8b6ad",
        borderColor: "#e2dfd5",
        label: "Moon",
        description: "Dynamic circular body",
        collisionRole: 1,
      },
    },
  ],
};
